# Generated by Django 3.2 on 2021-04-24 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCIW', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.png', upload_to='profile_picture'),
        ),
    ]
